# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Coding Standard"

on:
  push:
    paths:
      - "**.ts"
  pull_request:
    paths:
      - "**.ts"

jobs:
  CodingStandard:
    strategy:
      matrix:
        os: [ubuntu-latest]
        deno: ["1.2.0"]

    name: "Deno ${{ matrix.deno }} lint on ${{ matrix.operating-system }} OS"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: "Set up Deno v${{ matrix.deno }}"
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}

      - name: "Deno Version"
        run: deno --version

      - name: "check code format"
        run: |
          deno fmt --check -q ./src
          deno fmt --check -q ./tests
          deno fmt --check -q ./mod
          deno fmt --check -q ./deps.ts
          deno fmt --check -q ./test.ts
          deno fmt --check -q ./test_deps.ts

      - name: "lint code"
        run: |
          deno lint --unstable -q ./src
          deno lint --unstable -q ./tests
          deno lint --unstable -q ./mod
          deno lint --unstable -q ./deps.ts
          deno lint --unstable -q ./test.ts
          deno lint --unstable -q ./test_deps.ts
